"""Auto-built editorial: a daily PoV and a rotating Product of the Day.

Both are unbylined and generated by the loop — no human author. They work with
zero configuration (rule-based, derived from the day's actual wire) and upgrade
to genuine LLM-written prose when USE_LLM_BRIEFS=1 + ANTHROPIC_API_KEY are set.
"""
from __future__ import annotations

import os
import time

from .config import PRODUCTS
from .enrich import complete, has_key

# A strong stance per dominant theme — this is where the "PoV" gets its spine.
STANCE = {
    "Ransomware": "Ransomware is no longer a security problem; it is a business-continuity one. Organizations still treating backups as an afterthought are choosing, in advance, to pay. The only durable answer is tested, immutable recovery — and the discipline to never fund the next attack.",
    "Zero-Day": "The gap between disclosure and mass exploitation is now measured in hours, not weeks. Patch velocity has quietly become a survival metric. If your emergency-patch process still runs on a monthly cadence, you are defending last decade's threat.",
    "Data Breach": "Every breach this week traces back to the same root: data kept long after its usefulness expired. Minimization is not a compliance checkbox — it is the cheapest breach-response strategy that exists, because attackers cannot steal what you never retained.",
    "Nation-State": "State-aligned intrusions keep proving that 'we're too small to be a target' is a fiction. Supply chains, managed-service providers, and identity brokers are the real front line — and they are everyone's problem, not just the Fortune 100's.",
    "Vulnerability": "A backlog of unpatched, internet-facing systems is not technical debt — it is an open invitation with a timestamp. Exposure management, not vulnerability counting, is the shift that separates teams that get breached from teams that get lucky.",
    "Malware": "Commodity loaders and stealers now feed a professionalized criminal supply chain. Defenders who chase individual samples will always be behind; the leverage is in the delivery and identity layers, where the same infrastructure serves a hundred campaigns.",
    "Phishing": "Awareness training has hit its ceiling. When AI can clone a voice and draft a flawless lure, the answer is architectural — phishing-resistant authentication and out-of-band verification — not asking humans to spot the unspottable.",
    "Supply Chain": "One poisoned dependency now compromises thousands downstream. Software provenance — knowing exactly what runs and where it came from — is graduating from nice-to-have to non-negotiable.",
    "AI Security": "AI has become an attack surface of its own. Prompt injection, model theft, and data leakage are not hypotheticals — they are this quarter's incidents. Teams shipping LLM features without guardrails are running unmonitored code paths straight to their data.",
    "Cloud": "Cloud breaches rarely start with a zero-day; they start with a misconfiguration and an over-permissioned identity. The boring work — least privilege and continuous posture checks — still prevents the spectacular headlines.",
    "Policy": "Regulation is finally forcing disclosure timelines and accountability. The organizations that treat this as a compliance burden will be outrun by those that treat transparency as a trust advantage.",
}
DEFAULT_STANCE = "The through-line across today's wire is speed: attackers are compressing the time from disclosure to exploitation, while defenders are still budgeting on annual cycles. Closing that tempo gap — in patching, in identity, in detection — is the single highest-leverage move available right now."


def _topic_counts(items: list[dict]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for i in items:
        for t in i.get("topics", []):
            counts[t] = counts.get(t, 0) + 1
    return counts


def pov(items: list[dict], now: float) -> dict:
    """Build the PoV of the Day. Rule-based by default; LLM-written if enabled."""
    counts = _topic_counts(items)
    top_topic = max(counts, key=counts.get) if counts else "Vulnerability"
    crit = sum(1 for i in items if i.get("severity", 0) >= 3)
    clusters = sum(1 for i in items if i.get("coverage", 1) > 1)
    lead = items[0] if items else None
    date_str = time.strftime("%B %-d", time.gmtime(now))

    # LLM path — genuine editorial prose.
    if has_key():
        heads = "\n".join(f"- {i['title']} ({i['source']})" for i in items[:10])
        prompt = (
            "Write a sharp, unbylined 150-word editorial 'Point of View' for a "
            "cybersecurity newspaper, based ONLY on today's top stories below. Take a "
            "clear, defensible stance and end with a concrete recommendation. No byline, "
            "no headline, no preamble — just 2 short paragraphs.\n\n" + heads
        )
        body = complete(prompt, os.environ["ANTHROPIC_API_KEY"], max_tokens=320, label="PoV")
        if body:
            paras = [p.strip() for p in body.split("\n") if p.strip()]
            return {"title": f"The Point of View — {date_str}", "dek": f"On {top_topic.lower()} and the tempo of the day.",
                    "paragraphs": paras, "generated": "llm", "top_topic": top_topic}

    # Rule-based path — data-driven, updates daily, no key required.
    lead_bit = f" The day's lead — “{lead['title']}” via {lead['source']} — sets the tone." if lead else ""
    p1 = (
        f"Of the stories crossing the ThreatWire desk this {date_str}, "
        f"{counts.get(top_topic, 0)} center on {top_topic.lower()}, with {crit} rated critical "
        f"and {clusters} confirmed across multiple independent wires.{lead_bit}"
    )
    p2 = STANCE.get(top_topic, DEFAULT_STANCE)
    return {"title": f"The Point of View — {date_str}", "dek": f"On {top_topic.lower()} and the tempo of the day.",
            "paragraphs": [p1, p2], "generated": "auto", "top_topic": top_topic}


def feature(now: float) -> dict:
    """Pick the Product of the Day (rotates by day-of-year) and build its page data."""
    day_index = int(time.strftime("%j", time.gmtime(now)))
    product = dict(PRODUCTS[day_index % len(PRODUCTS)])
    product["date_str"] = time.strftime("%B %-d, %Y", time.gmtime(now))

    if has_key():
        prompt = (
            f"Write a neutral ~220-word product profile for a cybersecurity newspaper's "
            f"'Product of the Day'. Product: {product['name']} by {product['vendor']} "
            f"({product['category']}). Cover what it does, why it matters, and where it fits. "
            f"No hype, no headline, no byline — just 2-3 short paragraphs.\n\n"
            f"Context: {product['one_liner']} {product['why']}"
        )
        body = complete(prompt, os.environ["ANTHROPIC_API_KEY"], max_tokens=420, label=product["name"])
        if body:
            product["deep_dive"] = [p.strip() for p in body.split("\n") if p.strip()]
            product["generated"] = "llm"
            return product

    product["generated"] = "auto"
    return product
